{{- if .Values.providers.github }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-app
type: Opaque
data:
  clientSecret: {{ .Values.providers.github.clientSecret | b64enc }}
{{- end }}
{{- if .Values.providers.htpasswd }}
---
apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
type: Opaque
data:
  htpasswd: {{ include "oauth.htpasswd" .Values.providers.htpasswd | b64enc }}
{{- end }}
