dataScienceClusterComponents:
  codeflare:
    managementState: Removed
  dashboard:
    managementState: Managed
  datasciencepipelines:
    managementState: Removed
  kserve:
    managementState: Managed
    serving:
      ingressGateway:
         certificate:
           secretName: knative-serving-cert
           type: SelfSigned
      managementState: Managed
      name: knative-serving
  kueue:
    managementState: Removed
  modelmeshserving:
    managementState: Removed
  ray:
    managementState: Removed
  trainingoperator:
    managementState: Removed
  trustyai:
    managementState: Removed
  workbenches:
    managementState: Managed
