{{- if gt .Values.gpuOperator.timeSlices 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: device-plugin-config
  namespace: nvidia-gpu-operator
data:
  GpuTimeSlices: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
          - name: nvidia.com/gpu
            replicas: {{ .Values.gpuOperator.timeSlices }}
{{- end }}
