apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.cluster.infraID }}
  name: {{ .Values.cluster.infraID }}-gpu-worker-{{ include "aws-nvidia-gpu-machinesets.az" $ }}
spec:
  {{- if and (.Values.desiredReplicas) (not .Values.autoscaling.enabled) }}
  replicas: {{ .Values.desiredReplicas }}
  {{- end }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.cluster.infraID }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.cluster.infraID }}-gpu-worker-{{ include "aws-nvidia-gpu-machinesets.az" $ }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.cluster.infraID }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: {{ .Values.cluster.infraID }}-gpu-worker-{{ include "aws-nvidia-gpu-machinesets.az" $ }}
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/gpu: ""
      taints:
        - key: nvidia.com/gpu
          value: ""
          effect: NoSchedule
      providerSpec:
        value:
          ami:
            id: {{ .Values.aws.ami }}
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ""
                volumeSize: 120
                volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ .Values.cluster.infraID }}-worker-profile
          instanceType: {{ .Values.instanceType }}
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: {{ include "aws-nvidia-gpu-machinesets.az" $ }}
            region: {{ .Values.aws.region }}
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - {{ .Values.cluster.infraID }}-worker-sg
          subnet:
            filters:
              - name: tag:Name
                values:
                  - {{ .Values.cluster.infraID }}-private-{{ include "aws-nvidia-gpu-machinesets.az" $ }}
          tags:
            - name: kubernetes.io/cluster/{{ .Values.cluster.infraID }}
              value: owned
          userDataSecret:
            name: worker-user-data
