---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authorino
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: in-cluster
    namespace: openshift-operators
  project: default
  source:
    path: charts/authorino
    repoURL: git@github.com:jharmison-redhat/openshift-setup.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../clusters/athena.sandbox844.opentlc.com/cluster.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 3
        maxDuration: 30m
