---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Values.name | default (.Release.Name | printf "%s-%s" .Chart.Name) }}
spec:
  {{- with .Values.users }}
  users:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.initSQL }}
  databaseInitSQL:
    name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}-sql-init
    key: init.sql
  {{- end }}
  {{- with .Values.recoveryVolumes }}
  dataSource:
    volumes:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  postgresVersion: {{ default .Chart.AppVersion .Values.version }}
  instances:
  - name: instance1
    replicas: {{ .Values.replicas }}
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.size }}
    resources:
      {{- toYaml .Values.instanceResources | nindent 6 }}
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                postgres-operator.crunchydata.com/cluster: {{ .Values.name | default (.Release.Name | printf "%s-%s" .Chart.Name) }}
                postgres-operator.crunchydata.com/instance-set: instance1
  backups:
    pgbackrest:
      repoHost:
        resources:
          {{- toYaml .Values.backrestRepoResources | nindent 10 }}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.size }}
